[dlg TestMenuName]
Ruby Test Menu[w][e]

[sel TestMenu]
[s]Menu 1[f 4 26 0 184][e]
[s]Menu 2[f 4 26 1 185][e]
[s]Menu 3[f 4 26 2 186][e]

[dlg GENERIC_HELP_184]
[s]Opens Menu Entry 1.[e]

[dlg GENERIC_HELP_185]
[s]Opens Menu Entry 2.[e]

[dlg GENERIC_HELP_186]
[s]Opens Menu Entry 3.[e]

[dlg Menu1MSGName]
Test Menu 1[w][e]

[dlg Menu2MSGName]
Test Menu 2[w][e]

[dlg Menu3MSGName]
Test Menu 3[w][e]

[sel Menu1MSGMenu]
[s]Open Entry[f 4 26 0 187][e]

[sel Menu2MSGMenu]
[s]Open Entry[f 4 26 1 188][e]

[sel Menu3MSGMenu]
[s]Open Entry[f 4 26 2 189][e]

[dlg Menu1]
[s]If you see this, it works![n]Menu Entry 1![e]

[dlg Menu2]
[s]If you see this, it works![n]Menu Entry 2![e]

[dlg Menu3]
[s]If you see this, it works![n]Menu Entry 3![e]

[dlg GENERIC_HELP_187]
[s]Name says it.[e]

[dlg GENERIC_HELP_188]
[s]Name says it.[e]

[dlg GENERIC_HELP_189]
[s]Name says it.[e]