[msg MSG_BLANK]
[s]......[n][w][e]

[msg MND_PHONE_NG_000_00]
[s]Ich habe keine neue Nachrichten.[n][w][e]

[msg MSG_TEST_FLD]
[s]フィールド中□メニュー呼び出し。[n][w][e]

[msg MSG_TEST_DNG]
[s]ダンジョン中□メニュー呼び出し。[n][w][e]

[msg MSG_TEST_CELLPHONE_000]
[s]Es scheint, als gäbe es keine neuen[n]Infos dazu, wer einen Palast hat ...[n][w][e]

[msg MSG_TEST_CELLPHONE_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]そうそうすぐにパレスを持ったヤツが[n]見つかるわけないにゃ。[n][w][e]
[s][f 4 10 65535 0 0]しばらくはそのサイトに書かれた小物を[n]メメントスで片付けて力を付けるのがいいにゃ。[n][w][e]

[msg MSG_TEST_CELLPHONE_002 [Ryuji]]
[s][f 5 14]そっち情報なんか見っかったか?[n][w][e]

[msg HELP_MEMENTOS_MISSION_04 [Eine Mission steht bereit!]]
[s][clr 4]Mementos-Infos erhalten[clr 27][n]Du kannst jetzt vom [clr 2]Versteck[clr 27] aus[n]Prangerkarten verschicken. Manchmal[n]erhältst du so Infos von [clr 3]Kameraden[clr 27].[n][w][e]

[msg MSG_SPOT_AFTERNOON_ERROR]
[s]Ich sollte jetzt zu den[n]Tickettoren gehen ...[n][w][e]

[msg MSG_SPOT_NIGHT_ERROR]
[s]Ich bin ziemlich müde.[n]Ich sollte ins Bett gehen ...[n][w][e]

[msg MSG_IN_KF_EVENT]
[s]Jetzt ist nicht die Zeit dafür,[n]woanders hinzugehen.[n][w][e]

[msg MSG_IN_KF_EVENT_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Jetzt ist nicht die Zeit,[n]woanders hinzugehen.[n][w][e]

[msg MSG_NG_ROJIURA_OUT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Nachts ist es gefährlich in[n]der Stadt! Da brauchst du ein[n]unerschütterliches Herz.[n][w][e]
[s][f 4 10 65535 0 0]Wenn du nachts raus möchtest,[n]brauchst du genug [f 4 11 3][clr 26][f 4 12 3][clr 27],[n]um [clr 1]Nerven aus Stahl[clr 27] zu haben.[n][w][e]

[msg MSG_NG_GO_OUT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Du bist ganz sicher erschöpft.[n]Gehen wir schlafen.[n][w][e]

[msg MSG_GO_OUT_FRIEND [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Willst du wirklich rausgehen,[n]während ein Freund zu Gast ist?[n][w][e]

[sel SEL_GO_OUT_FRIEND top]
[s]Ausgehen[e]
[s]Abbrechen[e]

[msg MND_CHK_DOOR_playroom]
[s]Mein Teamkamerad kam aber gerade ...[n][w][e]

[sel SEL_PC_PLAYROOM_CHK top]
[s]Ausgehen[e]
[s]Zu Hause bleiben[e]

[msg MND_MAIL_NG]
[s]Ich bin heute zu müde. Ich[n]gehe besser ein anderes Mal raus ...[n][w][e]

[msg MND_NG]
[s]Das ist nicht der richtige Zeitpunkt ...[n][w][e]

[msg MND_SAVE_NG_COMMON]
[s]Das ist nicht der richtige Zeitpunkt ...[n][w][e]

[msg STOP_OUTDOOR_DEFAULT_MOR [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Wir sollten jetzt erst mal ins Bett[n]gehen, okay?[n][w][e]

[msg STOP_OUTDOOR_DEFAULT]
[s]Ich sollte schlafen gehen ...[n][w][e]

[msg MSG_GO_DUNGEON_TODAY_MOR [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0]Bist du nicht erschöpft?[n]Du solltest dich ausruhen.[n][w][e]

[msg MND_GO_DUNGEON_TODAY]
[s]Ich bin noch müde von[n]dem Meta-Universum. Ich[n]sollte mich ausruhen ...[n][w][e]

[msg MND_GO_SPOT_TODAY]
[s]Ich bin noch müde von dem Spaß[n]heute. Ich sollte mich in meinem[n]Zimmer ausruhen ...[n][w][e]

[msg MSG_STOP_NO_DEBUG2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0]日常進行でイベントが発生するÈ[n]キーフリーが出来ない仕様です。[n][w][e]

[msg MSG_QR_HIT]
[s]Wenn du in der Stadt das Dritte[n]Auge einsetzt, entdeckst du[n]gelegentlich [clr 2]QR-Codes[clr 27].[n][w][e]
[s]Mit diesen Codes kannst du Punkte[n]sammeln, um in der Anwendung[n][clr 2]PERSONAS O.A.[clr 27] Personas zu rufen.[n][w][e]
[s]Es gibt insgesamt [clr 2]100[clr 27] QR-Codes,[n]die an verschiedenen Tagen an[n]verschiedenen Orten zu finden sind.[n][w][e]
[s]Also nutze das Dritte Auge in der[n]Stadt, um QR-Codes zu entdecken.[n][w][e]

[msg MSG_SAVE_EPISODE_000_00 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1163 0 0]Du führst fleißig Tagebuch, hm?[n]Nun, ich hoffe, dass die Leute[n]bald besser von dir denken.[n][w][e]

[msg MSG_SAVE_EPISODE_001_00 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1025 0 0]Du führst fleißig Tagebuch, hm?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Wäre schön, wenn dir das richtig[n]helfen würde und zum Beispiel deine[n]Strafakte tilgen könnte ...[n][w][e]

[msg MSG_SAVE_EPISODE_002_00 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1187 0 0]Du führst fleißig Tagebuch, hm?[n]Klug. Vielleicht kannst du damit[n]mal beweisen, dass du recht hast.[n][w][e]

[msg MSG_SAVE_EPISODE_003_00 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1178 0 0]Du führst fleißig Tagebuch, hm?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Du wurdest schon ziemlich ungerecht[n]behandelt, nicht wahr?[n][w][e]

[msg MSG_SAVE_EPISODE_004_00 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1192 0 0]Du führst fleißig Tagebuch, hm?[n][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Weißt du, wenn ich so darüber[n]nachdenke, hat sich für uns beide[n]viel geändert, meinst du nicht?[n][w][e]

[msg MSG_SAVE_EPISODE_005_00 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1170 0 0]Du führst fleißig Tagebuch, hm?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Ich wünschte, wir könnten etwas[n]gegen deine Strafakte unternehmen.[n][w][e]

[msg MSG_SAVE_EPISODE_006_00 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1167 0 0]Du führst fleißig Tagebuch, hm?[n][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Zu schade, dass du dadurch nicht[n]reinen Tisch machen kannst ...[n][w][e]

