[dlg TestMenuName]
Ruby Test Menü[w][e]

[sel TestMenu]
[s]Menü 1[f 4 26 0 184][e]
[s]Menü 2[f 4 26 1 185][e]
[s]Menü 3[f 4 26 2 186][e]

[dlg GENERIC_HELP_184]
[s]Öffnet Menü Eintrag 1.[e]

[dlg GENERIC_HELP_185]
[s]Öffnet Menü Eintrag 2.[e]

[dlg GENERIC_HELP_186]
[s]Öffnet Menü Eintrag 3.[e]

[dlg Menu1MSGName]
Test Menü 1[w][e]

[dlg Menu2MSGName]
Test Menü 2[w][e]

[dlg Menu3MSGName]
Test Menü 3[w][e]

[sel Menu1MSGMenu]
[s]Öffne Eintrag[f 4 26 0 187][e]

[sel Menu2MSGMenu]
[s]Öffne Eintrag[f 4 26 1 188][e]

[sel Menu3MSGMenu]
[s]Öffne Eintrag[f 4 26 2 189][e]

[dlg Menu1]
[s]Wenn du das siehst, klappt es![n]Menü Eintrag 1![w][e]

[dlg Menu2]
[s]Wenn du das siehst, klappt es![n]Menü Eintrag 2![w][e]

[dlg Menu3]
[s]Wenn du das siehst, klappt es![n]Menü Eintrag 3![w][e]

[dlg GENERIC_HELP_187]
[s]Name sagt alles.[e]

[dlg GENERIC_HELP_188]
[s]Name sagt alles.[e]

[dlg GENERIC_HELP_189]
[s]Name sagt alles.[e]